import Head from 'next/head';
import Header from '../components/Header';
import Banner from '../components/Banner';
import Content from '../components/Content';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Netty App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
          <h1 className={styles.judul}>Create Collection</h1>
          <p className={styles.subJudul}>This images will appear on your collection</p>
        
        <Banner/>

        <Content />

      </main>


    </div>
  )
}
